#
#  persistent configuration options
#
#  see also DISTRO_SPECS
#
#  **NOTE**: check the original file every once in a while
#            settings might be added or removed...
#

## packages to build from source
PETBUILDS="gexec yad ram-saver spot-pkexec labwc wlopm chayang zzzfm mdview pup_advert_blocker"
[ "$DISTRO_TARGETARCH" = "x86_64" ] && PETBUILDS="$PETBUILDS efilinux"
PETBUILDS="$PETBUILDS labwc-puppy xdg-puppy-labwc fixmenusd"
[ "$DISTRO_VARIANT" != "barebones" ] && PETBUILDS="$PETBUILDS notification-daemon-stub mtpaint deadbeef gmeasures fpm2 xpad ExpenseTracker gfnrename wly-colpick gplaces"

## compression method to be used (SFS files)
SFSCOMP='-x0 -zlz4hc,12 -C262144'
