#!/bin/sh
text="Run $@ as root?"
exec yad --layer=overlay --title pkexec --window-icon=dialog-password --image=dialog-password --text "$text" --form --button="gtk-no:1" --button="gtk-yes:0" --response=1