#
#  persistent configuration options
#
#  see also DISTRO_SPECS
#
#  **NOTE**: check the original file every once in a while
#            settings might be added or removed...
#

## packages to build from source
PETBUILDS="rtclock ram-saver spot-pkexec psuspend pup_advert_blocker"
[ "$DISTRO_VARIANT" != "cli" ] && PETBUILDS="$PETBUILDS gexec yad chayang zzzfm mdview"
[ "$DISTRO_TARGETARCH" = "x86_64" ] && PETBUILDS="$PETBUILDS efilinux"
if [ "$DISTRO_VARIANT" = "dwl" ]; then
    PETBUILDS="$PETBUILDS dwl yambar-dwl"
elif [ "$DISTRO_VARIANT" != "cli" ]; then
    PETBUILDS="$PETBUILDS labwc-puppy xdg-puppy-labwc fixmenusd"
fi
[ "$DISTRO_VARIANT" != "cli" -a "$DISTRO_VARIANT" != "barebones" ] && PETBUILDS="$PETBUILDS notification-daemon-stub"
[ "$DISTRO_VARIANT" != "cli" -a "$DISTRO_VARIANT" != "barebones" -a "$DISTRO_VARIANT" != "mini" ] && PETBUILDS="$PETBUILDS deadbeef gmeasures fpm2 xpad ExpenseTracker gfnrename wly-colpick gplaces"

## compression method to be used (SFS files)
SFSCOMP='-x0 -zzstd,19 -C262144'
[ "$DISTRO_COMPAT_KERNEL_VERSION" != "bookworm" ] || SFSCOMP='-x0 -zlz4hc,12 -C262144'
