#!/bin/ash

#set -x

export TEXTDOMAIN=logout_gui

MSG_X="$(gettext "Active graphical server"): <b>Wayland</b>"
MSG_WM="$(gettext "Active window manager"): <b>$(cat /etc/windowmanager)</b>"

exec yad \
    --title "$(gettext 'Puppy Log Out')" \
    --window-icon=gtk-preferences \
    --text="${MSG_WM=}\n${MSG_X=}" \
    --text-align=center \
    --form \
    --align=center \
    --columns=2 \
    --field "$(gettext Reboot)"\!system-reboot-symbolic:FBTN "wmreboot; kill \$YAD_PID" \
    --field "$(gettext 'Shut Down')"\!system-shutdown-symbolic:FBTN "wmpoweroff; kill \$YAD_PID" \
    --field "$(gettext 'Restart graphical server')"\!view-refresh-symbolic:FBTN "restartwm; kill \$YAD_PID" \
    --field "$(gettext 'Exit to Prompt')"\!application-exit-symbolic:FBTN "wmexit; kill \$YAD_PID" \
    --field "$(gettext 'Rebuild Menu')"\!open-menu-symbolic:FBTN "fixmenus; killall -HUP labwc; kill \$YAD_PID" \
    --field "$(gettext 'Lock screen')"\!system-lock-screen-symbolic:FBTN "puplock; kill \$YAD_PID" \
    --no-buttons \
    --use-interp
