#!/bin/ash

. /etc/rc.d/PUPSTATE #PUPMODE

if [ "$PUPMODE" != "13" ] ; then
	exit
fi

case $1 in

 cli)
	echo
	echo -n "* Running in"
	echo -en "\\033[1;36m PUPMODE 13 \\033[0;39m "
	echo "(saving changes to RAM)"
	echo -n "* Type "
	echo -en "\\033[1;31msave2flash\\033[0;39m "
	echo "whenever you want to save session to pupsave"
	echo
	;;

esac

