#!/bin/sh
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)

. /etc/rc.d/PUPSTATE
if [ $PUPMODE -ne 13 ] ; then
	echo "save2flash: Wrong PUPMODE ($PUPMODE)"
	exit 1
fi

if pidof -s `cat /etc/windowmanager 2>/dev/null` >/dev/null 2>&1 ; then
	if [ -z "$DISPLAY" ] ; then
		export DISPLAY=':0'
	fi
	if [ -z "$WAYLAND_DISPLAY" ] ; then
		export WAYLAND_DISPLAY='wayland-0'
	fi
	if [ -z "$XDG_RUNTIME_DIR" ] ; then
		export XDG_RUNTIME_DIR='/tmp/runtime-root'
	fi
fi

if [ -n "$DISPLAY" -o -n "$WAYLAND_DISPLAY" ] ; then
	yad --image=document-save --layer=overlay --edge=bottomright --text="$(gettext "Saving RAM to 'pup_save'...")" --no-buttons &
	YAFPID=$!
else
	echo "Saving RAM to 'pup_save'..."
fi

nice -n 19 flock -Fx /tmp/snapmergepuppy.lock snapmergepuppy
[ "$YAFPID" ] && kill $YAFPID

exit 0

### END ###
