#!/bin/bash -e

. ./_00func
clearenv

. ./DISTRO_SPECS
. ./_00build.conf
. ./DISTRO_PKGS_SPECS-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}

case "$DISTRO_TARGETARCH" in
x86_64) ARCH=amd64 ;;
x86) ARCH=i386  ;;
arm) ARCH=armhf ;;
arm64) ARCH=arm64 ;;
*) exit 1 ;;
esac

case "$DISTRO_BINARY_COMPAT" in
debian) MIRROR=http://deb.debian.org/debian ;;
devuan) MIRROR=http://deb.devuan.org/merged ;;
*) exit 1 ;;
esac

mkdir -p sandbox3
cd sandbox3

CACHE_DIR=`pwd`/../local-repositories
mkdir -p "$CACHE_DIR"
TARBALL="${CACHE_DIR}/debootstrap.tar.gz"

rm -rf rootfs

[ -e ${TARBALL} ] || debootstrap --arch=$ARCH --variant=minbase --make-tarball=${TARBALL} ${DISTRO_COMPAT_VERSION} rootfs ${MIRROR}

# create a tiny installation of the compatible distro
debootstrap --arch=$ARCH --variant=minbase --unpack-tarball=${TARBALL} ${DISTRO_COMPAT_VERSION} rootfs ${MIRROR}

rm -f rootfs/etc/resolv.conf
cat /etc/resolv.conf > rootfs/etc/resolv.conf

[ ! -d ${CACHE_DIR}/archives ] || cp -r ${CACHE_DIR}/archives/* rootfs/var/cache/apt/archives/

# configure the package manager
case "$DISTRO_BINARY_COMPAT" in
debian)
	case "$DISTRO_COMPAT_VERSION" in
	sid)
		cat << EOF > rootfs/etc/apt/sources.list.d/${DISTRO_BINARY_COMPAT}.sources
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_COMPAT_VERSION}
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/${DISTRO_BINARY_COMPAT}-archive-keyring.gpg
EOF
		;;
	*)
		cat << EOF > rootfs/etc/apt/sources.list.d/${DISTRO_BINARY_COMPAT}.sources
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_COMPAT_VERSION} ${DISTRO_COMPAT_VERSION}-updates
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/${DISTRO_BINARY_COMPAT}-archive-keyring.gpg

Types: deb
URIs: ${MIRROR}-security
Suites: ${DISTRO_COMPAT_VERSION}-security
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/${DISTRO_BINARY_COMPAT}-archive-keyring.gpg
EOF
		;;
	esac
	;;

devuan)
	case "$DISTRO_COMPAT_VERSION" in
	ceres)
		cat << EOF > rootfs/etc/apt/sources.list.d/${DISTRO_BINARY_COMPAT}.sources
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_COMPAT_VERSION}
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/${DISTRO_BINARY_COMPAT}-archive-keyring.gpg
EOF
		;;
	*)
		cat << EOF > rootfs/etc/apt/sources.list.d/${DISTRO_BINARY_COMPAT}.sources
Types: deb
URIs: ${MIRROR}
Suites: ${DISTRO_COMPAT_VERSION} ${DISTRO_COMPAT_VERSION}-updates
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/${DISTRO_BINARY_COMPAT}-archive-keyring.gpg

Types: deb
URIs: ${MIRROR}-security
Suites: ${DISTRO_COMPAT_VERSION}-security
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/${DISTRO_BINARY_COMPAT}-archive-keyring.gpg
EOF
		;;
	esac
	;;
esac
rm -f rootfs/etc/apt/sources.list
cat << EOF > rootfs/etc/apt/apt.conf.d/00puppy
APT::Install-Recommends "false";
APT::Install-Suggests "false";
APT::Autoremove::SuggestsImportant "false";
EOF
chroot rootfs apt-get update
chroot rootfs apt-get upgrade -y

chroot rootfs apt-get install -y extrepo
chroot rootfs extrepo enable librewolf
chroot rootfs apt-get update

# install all packages
PKGS=`echo "$PKGS_SPECS_TABLE" | grep ^yes | grep -vF -e "exe>dev" -e "exe>null" | cut -f 3 -d \| | tr , '\n'`
chroot rootfs apt-get install -y $PKGS

# impersonate Puppy
install -m 644 ../DISTRO_SPECS rootfs/etc/DISTRO_SPECS

# install development packages to devx
rm -rf devx
cp -a rootfs devx
PKGS=`echo "$PKGS_SPECS_TABLE" | grep ^yes | grep -F "exe>dev" | cut -f 3 -d \| | tr , " "`
chroot devx apt-get install -y $PKGS

# create an archive of downloaded packages
cp -r devx/var/cache/apt/archives ${CACHE_DIR}/

# remove any unneeded packages
chroot rootfs apt-get autoremove -y --purge

# remove unneeded files
chroot rootfs apt-get clean
rm -f rootfs/var/lib/apt/lists/* 2>/dev/null || :
rm -rf rootfs/etc/resolv.conf rootfs/run/* rootfs/var/log/* rootfs/var/cache/man rootfs/var/cache/fontconfig rootfs/var/cache/ldconfig rootfs/usr/share/mime/mime.cache rootfs/etc/ld.so.cache
rm -rf `find rootfs -name __pycache__`
