#!/bin/bash
#v0.3 created by sc0ttman, August 2010: http://murga-linux.com/puppy/viewtopic.php?t=59290
#GPL license /usr/share/doc/legal/gpl-2.0.txt
#100830 BK added GPL license, amended Exit msg, bug fixes.
#120202 rodin.s: adding gettext
#140212 zigbert: gui (gtkdialog) improvements.

# advert blocker
# downloads a list of known advert servers
# then appends them to /etc/hosts so that
# many online adverts are blocked from sight

# make a hosts file if none found, or add a marker

export TEXTDOMAIN=pup-advert-blocker
export TEXTDOMAINDIR=/usr/share/locale
export OUTPUT_CHARSET=UTF-8
eval_gettext () {
  local myMESSAGE=$(gettext "$1")
  eval echo \"$myMESSAGE\"
}
export LANGORG=$LANG
HOSTS=$2
[ -z "$HOSTS" ] && HOSTS=/etc/hosts
export HOSTS

if [ ! -f $HOSTS ];then
	echo "#host file
127.0.0.1 localhost puppypc
" > $HOSTS
fi

# set vars
export appver='0.3'
export title='Pup Advert Blocker'
# the markers used to find the changes in /etc/hosts, which are made by this app
export markerstart='# pup-advert-blocker IPs below'
export markerend='# pup-advert-blocker IPs above'

# cleanup all leftover files
cleanup () {
	# remove all temp files
	rm -f /tmp/adlist-all /tmp/hosts-temp
}

# download the ads list
download_adlist () {
	wget -t 2 -O- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | grep '^0\.0\.0\.0' | grep -v '^0\.0\.0\.0 [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$' > /tmp/adlist-all
}

# creates an empty ad list
empty_adlist () {
	echo -n > /tmp/adlist-all
}
	
# append the list to the /etc/hosts
append_adlist () {
	# echo all but the stuff between the markers to a temp hosts file
	sed -e "/$markerstart/,/$markerend/d" $HOSTS > /tmp/hosts-temp
	# remove the markers
	sed -i -e "/$markerstart/d" /tmp/hosts-temp
	sed -i -e "/$markerend/d" /tmp/hosts-temp
	# add list contents into the hosts file, below a marker (for easier removal)
	echo "$markerstart" >> /tmp/hosts-temp
	# get contents of the downloaded adlist
	cat /tmp/adlist-all >> /tmp/hosts-temp
	echo "$markerend" >> /tmp/hosts-temp
	# replace the original with the cleaned version
	mv -f "/tmp/hosts-temp" "$HOSTS"
}

success () {
	# tell user 
	yad --title="$title" --window-icon=dialog-information --image=dialog-information --button=gtk-ok \
--text="$(gettext '<b>Success - your settings have been changed.</b>
Your hosts file has been updated.
Restart your browser to see the changes.')"
}

msg_help () {
echo "$title $(gettext "adds stuff to your '/etc/hosts' file, so that many advertising servers and websites will not be able to connect to this PC.
Blocking ad servers protects your privacy, saves you bandwidth, greatly improves web-browsing speeds and makes the internet much less annoying in general.")" > /tmp/box_help

yad --title="$title" --window-icon=dialog-information --text-info --filename=/tmp/box_help --wrap --button=gtk-ok &
}

# cleanup before start
cleanup

case "$1" in
  start)
    download_adlist
    append_adlist
    cleanup
    success
    ;;
  stop)
    empty_adlist
    append_adlist
    cleanup
    success
    ;;
  *)
    yad \
      --title="$title $appver" \
      --window-icon=gtk-execute \
      --text="$(gettext "Block online ads in all browsers with this simple tool")" \
      --form \
      --columns=2 \
      --field "$(gettext '<b>Start blocker</b>
Download and block the latest list of known advertising servers.')":LBL "" \
      --field "$(gettext '<b>Stop blocker</b>
Stop blocking known advertising servers.')":LBL "" \
      --field "$(gettext '<b>Edit host list</b>
Manually edit your hosts file in a text editor, adding or removing any entries you like.')":LBL "" \
      --field \!gtk-yes:FBTN "$0 start" \
      --field \!gtk-no:FBTN "$0 stop" \
      --field \!gtk-edit:FBTN "xdg-open /etc/hosts &" \
      --button=gtk-help \
      --button=gtk-quit \
      --use-interp
   if [ $? -eq 0 ]; then
     msg_help
     exec $0
   fi
   ;;
esac
