#!/bin/ash

gsettings set org.gnome.desktop.interface enable-animations false

# show all buttons in Firefox CSD
gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"

gsettings set org.gnome.software download-updates false
gsettings set org.gnome.software download-updates-notify false

xdg_autostart.sh
delayedrun &
