#!/bin/sh
# misc functions

# $1 = bytes
fx_format_bytes() {
	[ $1 ] || return
	local BYTES=$1
	local FORMATTEDSIZE="${BYTES}B" # bytes
	if [ ${BYTES} -ge 1099511627776 ] ; then
		FORMATTEDSIZE="`dc -e "$BYTES 1099511627776 2 k / p"`"
		FORMATTEDSIZE="`LANG=C printf "%.2f" $FORMATTEDSIZE`T" #terabytes
	elif [ ${BYTES} -ge 1073741824 ] ; then
		FORMATTEDSIZE="`dc -e "$BYTES 1073741824 1 k / p"`"
		FORMATTEDSIZE="`LANG=C printf "%.1f" $FORMATTEDSIZE`G" # gigabytes
	elif [ ${BYTES} -ge 1048576 ] ; then
		FORMATTEDSIZE="$(( $BYTES / 1048576 ))M" # megabytes
	elif [ ${BYTES} -ge 1024 ] ; then
		FORMATTEDSIZE="$(( $BYTES / 1024 ))K" # kilobytes
	fi
	echo "$FORMATTEDSIZE"
}

### END ###
