#!/bin/ash
#v2.14 Puppy now has XDG menus.
#this script builds the menus from template files.
#Any templates can be placed into /etc/xdg/templates, and the file must be
#named to show its final destination. For example, the template for JWM:
# _root_.jwmrc
#...the '_' will be converted to a '/', so the generated JWM config file is:
# /root/.jwmrc
# 5jan2008: fbpanel,lxpanel support developed by plinej.
#100427 when called via /etc/rc.d/rc.update, HOME is '/' (needed by some of the menu generating apps).
#120207 translation of some SSS strings. refer /usr/share/sss/menu_strings/
#120209 this script now called from /usr/sbin/quicksetup, whenever locale is changed.
#120216 sss translation file now uses simple sed expressions.

[ ! "$HOME" ] && HOME='/root'
[ "$HOME" = "/" ] && HOME='/root'
export HOME

LANG1="${LANG%_*}" #120207 ex: de

for ONESRC in `ls /etc/xdg/templates/_* 2>/dev/null` #ex: _root_.jwmrc
do
	ONEDEST=${ONESRC##*/}    # basename: _root_.jwmrc
	if [ "$HOME" != "/root" ] ; then
		ONEDEST=${ONEDEST//_root/$HOME} # _root.jwmrc -> /home/finn_.jwmrc
	fi
	ONEDEST=${ONEDEST//_/\/} # _root_.jwmrc -> /root/.jwmrc
	echo "Generating $ONEDEST..."
 
	[ -f $ONEDEST ] && mv -f $ONEDEST ${ONEDEST}-previous

	TMPDEST=`mktemp $ONEDEST.XXXXXXXXXX`

	while read ONELINE
	do
		case "$ONELINE" in PUPPYMENU*)
			EXECMENU="${ONELINE#PUPPYMENU }" #remove leading PUPPYMENU
			${EXECMENU} #>> ${TMPDEST}
			continue
		esac
		echo "$ONELINE" #>> ${TMPDEST}
	done < ${ONESRC} > ${TMPDEST}

	mv -f ${TMPDEST} ${ONEDEST}
done

###END###
