#!/bin/ash
# generic wrapper to run as ${XUSER} (when currently running as root)
# (C) James Budiono 2012, 2017
# License: GPL version 3 or later
#

XUSER=spot

case $0 in
run-as-spot|*/run-as-spot) ;;
*)
	XUSER=$1
	shift
	;;
esac

if [ ! -d /run/runtime ] ; then
	mkdir /run/runtime
	chmod 0700 /run/runtime
	chown ${XUSER}:${XUSER} /run/runtime
fi

# close all file descriptors except std{in,out,err}, in case one of
# them points to a file under /root
for FD in /proc/self/fd/*; do
	FD="${FD##*/}"
	[ $FD -gt 2 ] && eval "exec ${FD}<&-"
done

exec env -i \
	USER=${XUSER} \
	HOME=/home/${XUSER} \
	SHELL=/bin/bash \
	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games \
	TERM=linux \
	XDG_DATA_HOME=/home/${XUSER}/.local/share \
	XDG_CONFIG_HOME=/home/${XUSER}/.config \
	XDG_DATA_DIRS=/usr/share:/usr/local/share \
	XDG_CONFIG_DIRS=/etc/xdg \
	XDG_CACHE_HOME=/home/${XUSER}/.cache \
	XDG_RUNTIME_DIR=/run/runtime \
	XDG_STATE_HOME=/home/${XUSER}/.local/state \
	setpriv --reuid=`id -u ${XUSER}` --regid=`id -g ${XUSER}` --init-groups -- "$@"

### END ###
