#!/bin/sh
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)

. /etc/rc.d/PUPSTATE
if [ $PUPMODE -ne 13 ] ; then
	echo "save2flash: Wrong PUPMODE ($PUPMODE)"
	exit 1
fi

nice -n 19 flock -Fx /tmp/snapmergepuppy.lock snapmergepuppy

exit 0

### END ###
