#!/bin/sh
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)

. /etc/rc.d/PUPSTATE
if [ $PUPMODE -ne 13 ] ; then
	echo "save2flash: Wrong PUPMODE ($PUPMODE)"
	exit 1
fi

UID=`id -u`

if [ "$1" = "--home" -a $UID -ne 0 -a -d "/initrd/pup_ro1/${HOME}" ]; then
	nice -n 19 -- ionice -c 2 -n 7 -- flock -Fx /tmp/snapmergepuppy.lock snapmergepuppy /initrd/pup_ro1/home /initrd/pup_rw/home
	exit 0
fi

[ $UID -ne 0 ] && exec pkexec "$0" "$@"

if [ "$1" = "--home" ]; then
	nice -n 19 -- ionice -c 2 -n 7 -- flock -Fx /tmp/snapmergepuppy.lock snapmergepuppy /initrd/pup_ro1/home /initrd/pup_rw/home
else
	nice -n 19 -- ionice -c 2 -n 7 -- flock -Fx /tmp/snapmergepuppy.lock snapmergepuppy
fi

exit 0

### END ###
