#!/bin/bash
#v0.3 created by sc0ttman, August 2010: http://murga-linux.com/puppy/viewtopic.php?t=59290
#GPL license /usr/share/doc/legal/gpl-2.0.txt
#100830 BK added GPL license, amended Exit msg, bug fixes.
#120202 rodin.s: adding gettext
#140212 zigbert: gui (gtkdialog) improvements.

# advert blocker
# downloads a list of known advert servers
# then pass them to update-adlist so that
# many online adverts are blocked from sight

export TEXTDOMAIN=pup-advert-blocker
export TEXTDOMAINDIR=/usr/share/locale
export OUTPUT_CHARSET=UTF-8
eval_gettext () {
  local myMESSAGE=$(gettext "$1")
  eval echo \"$myMESSAGE\"
}

# set vars
export appver='0.3'
export title='Pup Advert Blocker'

success () {
	# tell user 
	yad --title="$title" --window-icon=dialog-information --image=dialog-information --button=gtk-ok \
--text="$(gettext '<b>Success - your settings have been changed.</b>
Restart your browser to see the changes.')"
}

msg_help () {
echo "$title $(gettext "downloads a list of blocked domains, so that many advertising servers and websites will not be able to connect to this PC.
Blocking ad servers protects your privacy, saves you bandwidth, greatly improves web-browsing speeds and makes the internet much less annoying in general.")" > /tmp/box_help

yad --title="$title" --window-icon=dialog-information --width=640 --height=240 --text-info --filename=/tmp/box_help --wrap --button=gtk-ok &
}

case "$1" in
  start)
    rm -f /var/cache/pup_advert_blocker/disabled
    nscd -i hosts
    success
    ;;
  stop)
    touch /var/cache/pup_advert_blocker/disabled
    nscd -i hosts
    success
    ;;
  update)
    curl -m 10 https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | grep '^0\.0\.0\.0' | grep -v '^0\.0\.0\.0 [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$' | sed 's/\s*#.*//g' | cut -f 2 -d ' ' | update-adlist
    nscd -i hosts
    success
    ;;
  *)
    yad \
      --title="$title $appver" \
      --window-icon=gtk-execute \
      --text="$(gettext "Block online ads in all browsers with this simple tool")" \
      --form \
      --columns=2 \
      --field "$(gettext '<b>Start blocker</b>
Start blocking known advertisnig servers.')":LBL "" \
      --field "$(gettext '<b>Stop blocker</b>
Stop blocking known advertising servers.')":LBL "" \
      --field "$(gettext '<b>Update list</b>
Download the latest list of known advertising servers.')":LBL "" \
      --field \!gtk-yes:FBTN "$0 start" \
      --field \!gtk-no:FBTN "$0 stop" \
      --field \!gtk-refresh:FBTN "$0 update" \
      --button=gtk-help \
      --button=gtk-quit \
      --use-interp
   if [ $? -eq 0 ]; then
     msg_help
     exec $0
   fi
   ;;
esac
