name: build

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      ref:
        type: string
        required: true
      name:
        type: string
      version:
        type: string
      arch:
        type: string
        required: true
      compat-distro:
        type: string
        required: true
      compat-distro-version:
        type: string
        required: true
      kernel:
        type: string
        required: true
      prefix:
        type: string
      artifact:
        type: string
        required: true
      retention:
        type: number
        required: true
      variant:
        type: string
      runner:
        type: string
        default: 'ubuntu-24.04'

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources petbuild-cache petbuild-output
    - name: Get cached local-repositories
      uses: actions/cache@v4
      with:
        path: local-repositories
        key: local-repositories-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-${{ inputs.variant }}-${{ github.sha }}
        restore-keys: |
          local-repositories-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-${{ inputs.variant }}-
          local-repositories-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-
    - name: merge2out
      timeout-minutes: 5
      run: |
        yes "" | sudo -E ./merge2out woof-distro/${{ inputs.arch }}/${{ inputs.compat-distro }}/${{ inputs.compat-distro-version }}
        sudo chown -R root:root ../woof-out_*
        sudo mkdir ../buildenv
        sudo cp -a ../woof-out_* ../buildenv/
    - name: Set name
      if: ${{ inputs.name != '' }}
      run: sudo sed -i 's/^DISTRO_NAME=.*/DISTRO_NAME="${{ inputs.name }}"/' ../woof-out_*/DISTRO_SPECS
    - name: Set version
      if: ${{ inputs.version != '' }}
      run: sudo sed -i s/^DISTRO_VERSION=.*/DISTRO_VERSION=${{ inputs.version }}/ ../woof-out_*/DISTRO_SPECS
    - name: Set file name prefix
      if: ${{ inputs.prefix != '' }}
      run: sudo sed -i s/^DISTRO_FILE_PREFIX=.*/DISTRO_FILE_PREFIX=${{ inputs.prefix }}/ ../woof-out_*/DISTRO_SPECS
    - name: Set variant
      if: ${{ inputs.variant != '' }}
      run: echo "DISTRO_VARIANT=${{ inputs.variant }}" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends debootstrap
        [ ${{ inputs.compat-distro }} != devuan ] || curl https://git.devuan.org/devuan/debootstrap/raw/branch/master/scripts/ceres | sudo tee /usr/share/debootstrap/scripts/`echo ${{ inputs.compat-distro-version }} | sed s/64$//`
    - name: 1download
      timeout-minutes: 120
      run: |
        sudo chown -R root:root local-repositories
        sudo mv local-repositories ../woof-out_*/
        cd ../woof-out_*
        sudo -E ./1download
    - name: Get cached kernel-kit output
      uses: dawidd6/action-download-artifact@v6
      with:
        repo: vanilla-dpup/woof-CE
        branch: vanilladpup-11.0.x
        workflow: ${{ startsWith(inputs.kernel, 'debian-') && 'dpup-kernel.yml' || (startsWith(inputs.kernel, 'ubuntu-') && 'upup-kernel.yml' || 'kernel-kit.yml') }}
        workflow_conclusion: success
        name: kernel-kit-output-usrmerge-${{ inputs.kernel }}-${{ inputs.arch }}
        path: output
    - name: Move cached kernel-kit output
      run: sudo mv output ../woof-out_*/kernel-kit/
    - name: Get cached petbuild-output
      uses: actions/cache@v4
      with:
        path: petbuild-output
        key: petbuild-output-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-${{ inputs.variant }}-${{ github.sha }}
        restore-keys: |
          petbuild-output-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-${{ inputs.variant }}-
          petbuild-output-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-
    - name: Get cached petbuild-cache
      uses: actions/cache@v4
      with:
        path: petbuild-cache
        key: petbuild-cache-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-${{ inputs.variant }}-${{ github.sha }}
        restore-keys: |
          petbuild-cache-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-${{ inputs.variant }}-
          petbuild-cache-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-
    - name: Get cached petbuild-sources
      uses: actions/cache@v4
      with:
        path: petbuild-sources
        key: petbuild-sources-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-${{ inputs.variant }}-${{ github.sha }}
        restore-keys: |
          petbuild-sources-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-${{ inputs.variant }}-
          petbuild-sources-${{ inputs.arch }}-${{ inputs.compat-distro }}-${{ inputs.compat-distro-version }}-
          petbuild-sources-${{ inputs.arch }}-${{ inputs.compat-distro }}-
          petbuild-sources-${{ inputs.arch }}-
          petbuild-sources-
    - name: 3builddistro
      timeout-minutes: 180
      run: |
        sudo chown -R root:root petbuild-{sources,cache,output}
        sudo mv petbuild-{sources,cache,output} ../woof-out_*/
        cd ../woof-out_*
        sudo -E ./3builddistro release
    - name: Build woof-CE.tar.gz
      run: |
        cd ../buildenv
        sudo mv ../woof-out_*/petbuild-sources ../woof-out_*/local-repositories woof-out_*/
        sudo tar -c -I "gzip -9" -f $GITHUB_WORKSPACE/woof-CE.tar.gz woof-out_*
        sudo mv woof-out_*/petbuild-sources woof-out_*/local-repositories $GITHUB_WORKSPACE/
    - name: Move build output
      run: |
        for i in `ls ../woof-out_*/woof-output-*/*.img 2>/dev/null`; do sudo gzip -1 $i; done
        for i in `ls ../woof-out_*/woof-output-*/*.{img.gz,iso} 2>/dev/null`; do sudo mv -f $i .; done
    - name: Move cache
      run: |
        sudo mv ../woof-out_*/petbuild-{cache,output} $GITHUB_WORKSPACE/
        sudo chown -R --reference ~ local-repositories petbuild-{sources,cache,output}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: |
          *.img.gz
          woof-CE.tar.gz
        retention-days: ${{ inputs.retention }}
