name: build

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      ref:
        type: string
        required: true
      name:
        type: string
      version:
        type: string
      arch:
        type: string
        required: true
      compat-distro:
        type: string
        required: true
      compat-distro-version:
        type: string
        required: true
      kernel:
        type: string
        required: true
      prefix:
        type: string
      artifact:
        type: string
        required: true
      retention:
        type: number
        required: true
      variant:
        type: string
      runner:
        type: string
        default: 'ubuntu-24.04'

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    container:
      image: debian:trixie-slim
      volumes:
        - /usr:/hostusr
      options: --privileged
    steps:
    - name: Free space
      run: rm -rf /hostusr/local/lib/android /hostusr/share/dotnet /hostusr/local/.ghcup /hostusr/share/swift # increase free space, we don't need these
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
    - name: Configure
      run: |
        DISTRO_COMPAT_VERSION=${{ inputs.compat-distro-version }}
        sed -i -e s/^DISTRO_BINARY_COMPAT=.*/DISTRO_BINARY_COMPAT=${{ inputs.compat-distro }}/ -e s/^DISTRO_COMPAT_VERSION=.*/DISTRO_COMPAT_VERSION=${DISTRO_COMPAT_VERSION%64}/ -e s/^DISTRO_TARGETARCH=.*/DISTRO_TARGETARCH=${{ inputs.arch }}/ -e 's/^DISTRO_NAME=.*/DISTRO_NAME="${{ inputs.name }}"/' -e s/^DISTRO_VERSION=.*/DISTRO_VERSION=${{ inputs.version }}/ -e s/^DISTRO_FILE_PREFIX=.*/DISTRO_FILE_PREFIX=${{ inputs.prefix }}/ DISTRO_SPECS
    - name: Set variant
      if: ${{ inputs.variant != '' }}
      run: echo "DISTRO_VARIANT=${{ inputs.variant }}" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -y --no-install-recommends xz-utils debootstrap
    - name: Prepare build environment
      timeout-minutes: 5
      run: |
        find -type f -name .gitignore -delete
        mkdir -p ../buildenv
        cp -a . ../buildenv/woof-CE
        rm -rf ../buildenv/woof-CE/.git
        mkdir -p $GITHUB_WORKSPACE/rootfs-skeleton/usr/local/share/woof-CE
        sh -c "tar -C ../buildenv -c woof-CE | xz -9 > $GITHUB_WORKSPACE/rootfs-skeleton/usr/local/share/woof-CE/woof-CE.tar.xz"
        cp -a rootfs-skeleton/usr/local/share/woof-CE ../buildenv/woof-CE/rootfs-skeleton/usr/local/share/
    - name: 1download
      timeout-minutes: 120
      run: ./1download
    - name: Get cached kernel-kit output
      uses: dawidd6/action-download-artifact@v6
      with:
        repo: vanilla-dpup/woof-CE
        branch: nomerge2out
        workflow: 'dpup-kernel.yml'
        workflow_conclusion: success
        name: kernel-kit-output-usrmerge-${{ inputs.kernel }}-${{ inputs.arch }}
        path: kernel-kit/output
    - name: 3builddistro
      timeout-minutes: 180
      run: ./3builddistro release
    - name: Build woof-CE.tar.gz
      run: |
        mv petbuild-sources local-repositories ../buildenv/woof-CE/
        tar -C ../buildenv -c -I "gzip -9" -f $GITHUB_WORKSPACE/woof-CE.tar.gz woof-CE
        mv ../buildenv/woof-CE/petbuild-sources ../buildenv/woof-CE/local-repositories .
    - name: Move build output
      run: |
        for i in `ls woof-output-*/*.img 2>/dev/null`; do gzip -1 $i; done
        for i in `ls woof-output-*/*.{img.gz,iso} 2>/dev/null`; do mv -f $i .; done
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: |
          *.img.gz
          woof-CE.tar.gz
        retention-days: ${{ inputs.retention }}
        compression-level: 0
