name: release

on:
  workflow_dispatch:
    branches:
      - testing
    inputs:
      name:
        description: 'Human-readable name'
        required: true
        default: 'dpup'
      version:
        description: 'Version number'
        required: true
        default: '11.0.0'
      suffix:
        description: 'Release name suffix, with leading -'
        required: false
        default: '-alpha1'
      arch:
        description: 'Architecture'
        required: false
        default: 'x86_64'
      compat-distro:
        description: 'Compatible distro'
        required: false
        default: 'debian'
      compat-distro-version:
        description: 'Compatible distro version'
        required: false
        default: 'trixie64'
      kernel:
        description: 'Kernel version'
        required: false
        default: 'debian-trixie'
      prefix:
        description: 'File name prefix'
        required: false
        default: 'dpup'
      release:
        type: boolean
        description: 'Upload release draft'
        required: false
      runner:
        type: choice
        description: 'Build environment'
        options:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
        default: 'ubuntu-24.04'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}     
      name: ${{ github.event.inputs.name }}
      version: ${{ github.event.inputs.version }}
      arch: ${{ github.event.inputs.arch }}
      compat-distro: ${{ github.event.inputs.compat-distro }}
      compat-distro-version: ${{ github.event.inputs.compat-distro-version }}
      kernel: ${{ github.event.inputs.kernel }}
      prefix: ${{ github.event.inputs.prefix }}
      artifact: ${{ github.workflow }}-${{ github.event.inputs.arch }}-${{ github.event.inputs.compat-distro }}-${{ github.event.inputs.compat-distro-version }}-${{ github.run_number }}
      runner: ${{ github.event.inputs.runner }}
      retention: 1
  upload:
    needs: build
    if: github.repository != 'puppylinux-woof-CE/woof-CE' && github.event.inputs.release == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.workflow }}-${{ github.event.inputs.arch }}-${{ github.event.inputs.compat-distro }}-${{ github.event.inputs.compat-distro-version }}-${{ github.run_number }}
          path: .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.prefix }}-${{ github.event.inputs.version }}${{ github.event.inputs.suffix }}
          tag_name: ${{ github.event.inputs.prefix }}-${{ github.event.inputs.version }}${{ github.event.inputs.suffix }}
          fail_on_unmatched_files: true
          files: |
            *.img.gz
            woof-CE.tar.gz
          draft: true
          prerelease: false
